import { Work_Sans } from 'next/font/google'
import './globals.css'

const font = Work_Sans(
  { 
    subsets: ['latin'],
    weight: ['400', '600', '700'] 
  }
  )

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
